version: '3'
services:
  db:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=quantize-app
      - POSTGRES_USER=secret
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  server:
    ports:
      - '9000:9000'
    environment:
      - FLASK_APP=api
      - SECRET_KEY=notsosecretkey
    depends_on:
      - db