version: '3'
services:
  db:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=quantize-app
      - POSTGRES_USER=secret
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=api
      - FLASK_ENV=DEVELOPMENT
    volumes:
      - ./server/:/app/
    depends_on:
      - db